# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_date', models.DateField()),
                ('preacher', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
