# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon_storer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='sermon_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='preacher',
        ),
        migrations.AddField(
            model_name='sermon',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sermon',
            name='filename',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sermon',
            name='scripture',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sermon',
            name='sermon_title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
