# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon_storer', '0002_auto_20171023_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='file_exists',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='sermon',
            name='tmp_filename',
            field=models.TextField(default=''),
        ),
    ]
