# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon_storer', '0004_auto_20171106_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='has_ftp_file',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='sermon',
            name='is_published_wordpress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sermon',
            name='pb_ep_id',
            field=models.TextField(default=''),
        ),
    ]
