# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthkey',
            name='refresh_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
