# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0002_oauthkey_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
