# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0003_delete_greeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthkey',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='oauthkey',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthkey',
            name='expires_at',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
