# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0004_auto_20171102_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oauthkey',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
